title: LINKED OPEN DATA AND COMPUTATIONAL SOCIAL SCIENCE METHODS
author: Ji Ma@UT Austin
subtitle: LBJ School of Public Affairs

url: "https://ma-ji.github.io"
baseurl: "/open_data"

footer_url: "https://github.com/pro-panda"
footer_text: "Theme by pro-panda"

# profile-picture: assets/profile.jpg
# favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Course Schedule"
   link: "course_schedule"
 - name: "Assignment"
   link: "assignment"
